name: build_and_run
on: [push]
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: rm -rf build && mkdir -p build && cmake -B build -S . && cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: 
            ./build/main
            ./build/runUnitTests

    tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: binaries
        - run: chmod +x run runUnitTests && runUnitTests

    run:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: binaries
        - run: chmod +x run main && main

#      - run: ./build/main 2 4
#      - run: ./build/runUnitTests
#      - run: ./build/runBenchmark

